### PR TITLE
Updates for v4

### PR DESCRIPTION
**Pull request by slembcke**
This are the changes necessary to get SpriteBuilder working against the incoming changes for v4. Asset loading for sprites works, Mac retina mode works, screen sized widgets work (rulers, guides and selection handles).

The only thing I know of that doesn't work is the close button on sticky notes. Last time I spoke with Viktor, the sticky notes weren't considered a high priority. I expect it will be an easy fix though.

This should be merged at the same time as https://github.com/spritebuilder/ObjectAL-for-Cocos2D/pull/6 and https://github.com/cocos2d/cocos2d-spritebuilder/pull/1277.

### CODE REVIEW

**Comment by slembcke** [comment]
Hmm. Looks like the tests failed because it doesn't know how to pull the git submodule from my branch (since it hasn't been merged yet). When I run `rake test`locally everything works.

**Comment by rkachowski** [comment]
Yeah, this will not be accessible to the build server (or publicly) until your linked PR is merged into cocos2d. Once that happens the build server will be able to run the tests.

**Comment by rkachowski** [comment]
I'm going to rebase this onto latest develop and try to merge asap

**Comment by rkachowski** [comment]
This is crashing in `-[PreviewView_Tests assertPropertiesAreSetToViewController:isAudio:properties:] + 512 (PreviewView_Tests.m:263)` due to some KVC issue. I will address this directly, merge the patch in and close this PR to resolve things

**Comment by rkachowski** [comment]
Merged

**Pull request closed without merging**
