### PR TITLE
UsageManager Singleton, More Events

### PR DESCRIPTION
**Pull request by cocojoe**
Made UsageManager a singleton and started adding more events.
This will be on going so better to get started collecting now and refactor events as we go.

### CODE REVIEW

**Comment by rkachowski** [comment]
Looks good to me :+1:

**Comment by NickyWeber** [comment]
Wow it is tracking names of projects? I am wondering if the mixture of event and value should be in one string but this I guess this is not the right place to discuss this.

Looks good to me too.

**Comment by cocojoe** [comment]
No it doesn't tracking anything like that :) More how many projects are Obj-C or Swift, which is interesting.

**Comment by NickyWeber** [comment]
Sorry my bad, misinterpreted this line: 

`[[UsageManager sharedManager] sendEvent:[NSString stringWithFormat:@"project_new_%@",saveDlgLanguagePopup.selectedItem.title]];`

**Pull request merged**
