### PR TITLE
Animations + dynamic physics type

### PR DESCRIPTION
**Pull request by bchessin**
In my project, I had a need to support animations for a few sprites/nodes that had dynamic physic bodies. After some testing, everything works well. I think this is a simple feature addition and will be beneficial to many. Related to this issue: https://github.com/spritebuilder/SpriteBuilder/issues/507#issuecomment-51417177

### CODE REVIEW

**Comment by bchessin** [comment]
Is there any specific reason why this has not been merged yet?

**Comment by NickyWeber** [comment]
I apologize, we are just very very busy at the moment.

**Comment by cocojoe** [comment]
OK am flagging this up to review.

**Comment by cocojoe** [comment]
See Notes in #507

**Pull request closed without merging**
