### PR TITLE
Fix compile error for Mac project

### PR DESCRIPTION
**Pull request by andykorth**
Just a missing import in the Mac app delegate.

### CODE REVIEW

**Comment by cocojoe** [comment]
odd? I've been creating Mac projects with no issues in develop.

**Comment by andykorth** [comment]
I guess you could compare your Mac/AppDelegate.m file to this one: https://github.com/andykorth/SpriteBuilder/blob/develop/Support/PROJECTNAME.spritebuilder/Source/Platforms/Mac/AppDelegate.m

I think you have to re-run the python script in order to get the changes in the template projects into the zip that is used by SpriteBuilder when you create a fresh project. Then after you have a fresh SpriteBuilder project, try the Mac target in Xcode. 

It was a pretty straightforward error, at least. But I am a bit fuzzy on the SpriteBuilder build process.

**Comment by NickyWeber** [comment]
Pretty weird, I guess CCPackageManager.h is not included in the cocos2d.h?

**Comment by collinjackson** [comment]
I don't think that import should need to be in the template. Most likely it just needs to be added to cocos2d.h. The Mac target works fine for me without that #import in SpriteBuilder 1.3.1-rc.1, I haven't tried develop.

**Comment by andykorth** [comment]
Ah, that's right. It's missing from cococs2d.h in develop-v4:
https://github.com/cocos2d/cocos2d-swift/blob/develop-v4/cocos2d/cocos2d.h

Let's close this spritebuilder issue and I'll fix it in cocos2d.h.

**Pull request closed without merging**
