### PR TITLE
Active stats timer

### PR DESCRIPTION
**Pull request by cocojoe**

### CODE REVIEW

**Comment by collinjackson** [comment]
I feel like we should only count the user as active if they've interacted with the app in some way. What do you think?

**Comment by cocojoe** [comment]
In general I'm not a great fan on this keep alive type stat (separate conversation).  Time can be based upon say 'open project' and 'close project/quit sb', if not logged can add of course. However this was requested.

**Comment by rkachowski** [comment]
If we want to track usage we should have some kind of more intelligent metrics, e.g. starting a timer on open and posting the results on close / next open. 

A 1 hour timer is not going to catch anyone active for less than an hour.

**Comment by NickyWeber** [comment]
We could...drums...also use timestamps to calculate the length of the session!

**Comment by collinjackson** [comment]
I talked with @RarefactionQ and @vlidholt about this, our current proposal is to track global mouseup events and only send such events at most 1 per hour. (So store a global timestamp of the last mouseup event sent and when a new event comes in, if the previous event happened in the last hour then just do nothing.) On the server side we can see unique mouseups per time period and use this to compute daily/weekly/monthly actives.

I don't think session length is needed at this point.

Martin does that make sense to you?

**Comment by cocojoe** [comment]
Let me just email you to clarify as I've interpreted this about 3 different ways :)

**Comment by cocojoe** [comment]
To be replaced.

**Pull request closed without merging**
