### PR TITLE
Remember main window frame position and panel settings

### PR DESCRIPTION
**Pull request by FahimF**
I asked for this feature on this forum thread:

http://forum.spritebuilder.com/t/feature-remember-window-size-position/1023

Similar functionality is also discussed in issue #424

Since there appeared to be no interest in implementing this, I decided to go ahead and implement it myself quickly :) This functionality could probably be cleaned up a bit to do a bit more but for the time being, this should achieve what I wanted. Hopefully, this can be merged into the code base.

### CODE REVIEW

**Comment by vlidholt** [comment]
Not merging this as it is not complete. Needs to also store the sizing of the split view. It also needs testing on plugging in a smaller display etc. The feature is on the roadmap ( #40  ), we will use this pull request as a starting point for implementing this feature.

**Comment by FahimF** [comment]
The split view size saving _is_ already there - unless you mean a different split view than the bottom one? I don't have a smaller display to test on so that part would have to be done by somebody who actually has a smaller display :) It would be nice to have some of this functionality now rather than waiting for down the line since if you're using SpriteBuilder on a daily basis, always having to set up your window again is an annoyance.

**Comment by FahimF** [comment]
Actually, testing for a smaller display turned out to be (literally) two minutes of work :) I simply had to change the screen resolution for my notebook and run SpriteBuilder again. You're right, the current code does not handle changing to a lower resolution, but fixing it should be about 10 minutes of work. If you'll accept this pull request once that is in place, let me know and I'll go ahead and do the work. If not, will not bother since there isn't a point :)

**Comment by NickyWeber** [comment]
Hey Fahim,
we really appreciate your efforts! It just take some time to get to the contributions. The downside of this is that merging your pull request is not trivial for the MainMenu.xib. There are many changes which can't be automatically merged. 

So I kindly ask you to merge the most recent revision of develop into your branch and file a pull request, I will merge it with high prio asap.

**I love the open last project feature!**

First of all the issues I found:
- The preview box in the left panel is misplaced after increasing the height of the main window and quitting/restarting. Have a look at the screenshots I posted
- The split panel's position in the left pane for File View and Tileless Editor View tab is not saved, see screenshot.

**Confirmed**: Different resolutions are **no problem**, This is solved with Apple's NSWindow's autosave propertiy. This behaves in a logical way, the window will never disappear instead moved as much as needed to be visible without being resized.

**resizing height increased preview - ok - original develop branch**
left_panel_resized_ok

**resizing height decreased preview - ok - original develop branch**
left_panel_shrunk_ok

**resizing preview not correct - your branch**
left_panel_error

**split view positions not saved**
leftpane_splitview_tileless

leftpane_splitview_fileview

**Comment by FahimF** [comment]
Hey Nick,

Thanks for the response and for pointing out the issues etc. With regards to the changes to the XIB files, there were no major changes - all that was done was to add a value for "Autosave" on Main Wndow and the central pane splitter :) 

I missed the fact that the left panel was a split view too. So in order to fix the positioning there, you simply need to set a value for "Autosave" on that split view too.

So, instead of me submitting another pull request, I'd be fine with you guys adding the "Autosave" value to the XIB file for the three elements in question - main window, split view on left panel, and split view on central panel. That should fix everything.

If you prefer not to have the "Autosave" values set in the XIB file, you could do the same thing via code too, if necessary.

**Comment by NickyWeber** [comment]
Hey Fahim,
all good, I'll give it a try today. Thanks for the details, it should suffice to do the changes myself. From the diff it looked more complicated and hard to backtrace what has actually been done.
Will let you know when I'm done.

**Comment by FahimF** [comment]
Yeah, it's all the unnecessary stuff that Xcode seems to do :) That's the thing I hate about using XIB files with Git.

**Comment by NickyWeber** [comment]
There we go.

**Pull request merged**
