### PR TITLE
Added keyboard shortcuts to swap between tabs using ctrl-tab keys

### PR DESCRIPTION
**Pull request by midair**
Added keyboard shortcuts to swap between the different opened .ccb file tabs using the ctrl-tab key to move forward and ctrl-shift-tab to move backward.

### CODE REVIEW

**Comment by cocojoe** [comment]
Thanks for the great contribution, I think we should open up the discussion for which key combinations should be used.  

For example `Xcode` uses `Cmd+Shift+[` and `Cmd+Shift+]` to cycle tabs so I'm leaning towards that.

**Comment by midair** [comment]
Okay! I implemented it using the key combination that I usually use when navigating Chrome (don't use Xcode tabs often), but I see the benefits of paralleling Xcode, so I can submit a new pull request if that is preferred.

**Comment by cocojoe** [comment]
Great, just commit changes to your `tabKeyboardShortcut` branch

**Comment by midair** [comment]
I updated the key-bindings. Let me know if you need anything else!

**Comment by cocojoe** [comment]
Excellent, looks good. This is a little nit picky however for consistency inline with Xcode, it should be `Show Next/Previous Tab` vs `Select Next/Previous Tab`

@vlidholt Please can you review the UI change and functionality in this.  Here is a screenshot of the Window menu, pre change above.

screenshot 2015-01-15 12 17 54

Thanks

**Comment by midair** [comment]
Ah, yep! I've changed it to say "Show".

**Comment by cocojoe** [comment]
Great thanks.

**Pull request merged**
