### PR TITLE
change plugin inspector CBBPProperties from .plist to .json

### PR DESCRIPTION
**Pull request by stuartcarnie**
- used `plutil` to mass convert, so it was not lossy and will guarantee no human error
- `NSJSONSerialization` is much faster than properties lists
  - http://stackoverflow.com/questions/7559340/performance-of-nspropertylistserialization-vs-nsjsonserialization
- must less verbose
- will be able to create a json schema to validate the .json files
- easier to read
- spotted a few errors where `<string>` was used instead of `<integer>`

NOTE: `PluginNode` still supports .plist files, but tries to load
a CCBPProperties.json first.

### CODE REVIEW

**Comment by stuartcarnie** [comment]
As an example of the improvement:

**from this:**
(note how difficult it is to pull out key / value pairs)

```
<dict>      
   <key>readOnly</key>     
   <true/>     
   <key>defaultSerialization</key>     
   <array>     
       <integer>0</integer>        
       <integer>0</integer>        
   </array>        
   <key>type</key>     
   <string>Point</string>      
   <key>name</key>     
   <string>anchorPoint</string>        
   <key>displayName</key>      
   <string>Anchor point</string>       
</dict>
```

**to this:**

```
{
  "readOnly": true,
  "displayName": "Anchor point",
  "defaultSerialization": [0, 0],
  "type": "Point",
  "name": "anchorPoint"
},
```

**Comment by cocojoe** [comment]
Looks great, big fan of JSON format.

**Comment by thayerandrews** [comment]
I think @vlidholt will want to chime in on this change but I really like the readability improvement of the JSON data. Nice work.

**Comment by stuartcarnie** [comment]
thanks, @thayerandrews. I have worked a lot with .plist files in previous projects and switched to .json for the same reason – so much noise.

**Comment by vlidholt** [comment]
Ok, we probably don't want to change this until 2.0. Lots of people are using version control and this can potentially screw things up for them.

Thanks for the great updates Stuart! :)

**Comment by NickyWeber** [comment]
I am a big fan of json too, however the lack of comments is something I miss sometimes.

@stuartcarnie Can you please make another pull request targeting develop-v4, please?

**Comment by stuartcarnie** [comment]
My biggest gripe too, @NickyWeber. There is [an extension](https://github.com/blach/NSJSONSerialization-Comments) to `NSJSONSerialization`, if it becomes a problem

**Comment by stuartcarnie** [comment]
@vlidholt no worries!  

How do you see it screwing things up for them? Be interested to know, in case there is something I can do to mitigate the issues.

**Comment by stuartcarnie** [comment]
@NickyWeber does develop-v4 need a merge from develop, as last commit was early December

**Comment by NickyWeber** [comment]
I can arrange something on Monday, I think v4 is stale at the moment since everyone is working on 1.4 release. There will be more activity soon. V4 is the way to go for v2.0 as Vik mentioned.

**Comment by stuartcarnie** [comment]
No worries – it will be much simpler if develop-v4 is merged first and then I merge this into develop-v4

**Comment by vlidholt** [comment]
My thinking is that users can be working on the same file and if someone updates SB and the file format changes it would be very hard to merge any ccb-files.

We are about to release 1.4 very soon, after that we will merge the changes into a single develop branch (for SB 2.0 which will be the next version).

**Comment by stuartcarnie** [comment]
@vlidholt these changes are just to the inspector control files inside of SB, not the `.ccb` files :)  Only us SpriteBuilder devs will be working with them

**Comment by stuartcarnie** [comment]
@cocojoe, now that 1.4 has been released, I figured I'd bump this again since I've merged the latest

**Comment by cocojoe** [comment]
Yes, will discuss this tonight.

**Comment by cocojoe** [comment]
Closing due to inactivity.

**Pull request closed without merging**
