### PR TITLE
Project Template changes to support CCAppDirector

### PR DESCRIPTION
**Pull request by rkachowski**
These are the required project template changes required to support https://github.com/cocos2d/cocos2d-swift/pull/1217 and address #912 

**Don't merge this before the above cocos2d changes are available in SpriteBuilder's cocos2d submodule!**

The biggest change here is that most of the configuration has been taken out of SpriteBuilder's template files and pushed into cocos2d via a new `CCAppDirector` class. The template constructs a custom subclass for the user's application and uses it to start the configuration process for each platform. Checkout the PR on the cocos2d repository for more info on the reasons behind the changes here.

### CODE REVIEW

**Comment by cocojoe** [comment]
Still relevant and ready to go yet?

**Comment by slembcke** [comment]
This branch works for me on iOS 7/8, Mac and Android for me using the latest changes from https://github.com/cocos2d/cocos2d-swift/pull/1218.

**Comment by rkachowski** [comment]
Hey - yeah this should be fine, but the required cocos2d patches are neither in the cocos2d repo, nor in the cocos2d reference that SpriteBuilder is pointing at. Merging it now would be A Bad Idea™

**Comment by slembcke** [comment]
#1218 has been merged now. Is there anything else needed before this can be merged?

**Comment by rkachowski** [comment]
Sb Develop needs to have a cocos2d ref that points to the newest
functionality

**Pull request merged**
