### PR TITLE
Fixes #1247

### LINKED ISSUE #1247: Timeline node tree in wrong order
Issue was brought up here: http://forum.spritebuilder.com/t/timeline-node-tree-upside-down/2588

The timeline should order nodes from topmost highest zOrder to bottom lowest zOrder. This becomes most evident when adding a child to a parent. As an example adding a drop shadow. Almost always you would want the default to add the child behind the parent, not the other way around. Conceptually it makes no sense to have the item highest in the timeline be lowest in zOrder. All other editing programs work this way: After Effects, Photoshop, Flash, Unity etc...

### PR DESCRIPTION
**Pull request by stuartcarnie**
Adds a new user default with key `SEQUENCER_NODE_SORT_ORDER_REVERSE`,
which defaults to `NO` (meaning the sequencer nodes sort the original way)

To change the sort order, either launch the app via Terminal:

```
SpriteBuilder -SEQUENCER_NODE_SORT_ORDER_REVERSE YES
```

OR to change the sort order permanently

```
defaults write SpriteBuilder SEQUENCER_NODE_SORT_ORDER_REVERSE YES
```

### CODE REVIEW

**Comment by stuartcarnie** [comment]
I have not created any UI for this yet, as that would require a fair amount of work. This first step allows us to implement the feature and still be usable for power users. The beauty being that as soon as we add UI, it will reflect the user's current preferences.

**Comment by cocojoe** [comment]
Couldn't get a consensus on default behaviour so your suggest seems like a sensible way to do it, leave current behaviour as default and expose for advanced users.  In future we can always add to menu.

@stuartcarnie I can test this and it works fine if I manually change the reverseSort flag in code however I am unable to get 'SEQUENCER_NODE_SORT_ORDER_REVERSE YES' to work either via terminal or defaults.  I even copied it into Applications just in case.  Suggestions?

**Comment by stuartcarnie** [comment]
@cocojoe because the app is in a sandbox container, you can't write to the standard "SpriteBuilder" domain, because building via Xcode creates a new container for each build. If you look in `~/Library/Containers` you will see lots of `SpriteBuilder-*` folders. I will look at how the naming works, as the defaults API can specify a full path.

The CLI is the best way to test, however you should specify the full path to the `SpriteBuilder` executable for your newly built binary, such as 

```
$SBHOME/SpriteBuilder/build/Release/SpriteBuilder.app/Contents/MacOS/SpriteBuilder -SEQUENCER_NODE_SORT_ORDER_REVERSE YES
```

Let me know how you get on

**Comment by cocojoe** [comment]
@stuartcarnie You just want to update this to be default and drop the options?

**Comment by stuartcarnie** [comment]
@cocojoe just about to do that :+1:

**Comment by stuartcarnie** [comment]
@cocojoe done

**Comment by cocojoe** [comment]
All good.

**Pull request merged**
