### PR TITLE
Feature/#1160 package improvements

### PR DESCRIPTION
**Pull request by NickyWeber**
This implements the second point in https://github.com/spritebuilder/SpriteBuilder/issues/1160.

**Feature looks like this:**

bildschirmfoto 2014-12-04 um 18 43 31

**Working in a way like global auto scaling, override order is:**
`Per asset auto scaling > Package auto scaling > Global auto scaling`

This branch includes the feature as well as a few refactorings:
- New tests added to reflect per package auto scaling values
- Several tests have been adjusted in the course of refactoring
- Renamed PackagePublishSettings to SBPackageSettings
- ResourceManager's createCachedImageFromAuto method was renamed and split into several smaller methods
- ResourceManager's updatedWatchedPaths renamed to updateWatchedPaths
- Publishing and all its subsequent operations require an array of SBPackageSettings to work properly
- Application wide notifications have been altered to set the sender as object parameter and data put in the userInfo dictionary
- Several key constants have been added to access a notification's userInfo dictionary 
- Removed some debug NSLogs
- Some notification names renamed

A little side note: The inbetween solution of a SBPackageSetiingsManager was discarded due to the complexity of the ResourceManager.

### CODE REVIEW

**Comment by cocojoe** [comment]
Nicky when you get back can you fix the auto merge please and I'll review.  Be nice to get this in soon as would be beneficial for downloading asset packs with pre set scale.

**Comment by NickyWeber** [comment]
Still not merged? Pfffft.

**Comment by cocojoe** [comment]
Kind of forgot about it, sorry :)

**Comment by cocojoe** [comment]
Looks good

**Pull request merged**
