### PR TITLE
Added applesscript to spritebuilder which hooks up the publish command w...

### PR DESCRIPTION
**Pull request by osinoleg**
Added applesscript to spritebuilder which hooks up the publish command with xcode. Users can now publish the app via xcode build script phase.

### CODE REVIEW

**Comment by ebrodzki** [comment]
hooray!

**Comment by osinoleg** [comment]
feel free to ignore this pull request. A new one in incoming soon that includes a more complete solution.

**Comment by vlidholt** [comment]
Looking promising, let me know when you have finished this up! :)

**Comment by osinoleg** [comment]
Hey Viktor, I've pushed all the changes to the xcodePublish branch. Should
be good to go.

On a side note, next time you are in the office, I would like to get
together and see if I could help out with the SpriteBuilder project like
adding video nodes, etc..

**Comment by vlidholt** [comment]
Not sure which is the conflicting file, but I cannot merge this automatically.

For future reference, it would be great if you place the feature branches in your own fork. Just to keep the branches clean in the official repo.

Will be wfh tomorrow too, but will be in the office on Wed, let talk more then! :)

**Comment by osinoleg** [comment]
Got ya, np we can merge this in together.

**Pull request closed without merging**
