### PR TITLE
Light effect and node editing

### PR DESCRIPTION
**Pull request by thayerandrews**
Various lighting fixes:
- Make the shininess control more user friendly by limiting its range to [0..1]. This mirrors a similar change in the underlying CCEffect that I will submit next.
- Add support for hiding / showing light icons in the stage via the Document -> Show menu and the visibility controls in the Sequencer.

### CODE REVIEW

**Comment by NickyWeber** [comment]
Looks good. I got one concern: AppDelegate.m. The AppDelegate is a house with almost all windows broken, is it possible to move the details for lighting to another class and keep new code to the appdelegate to a minimum?

**Comment by thayerandrews** [comment]
That's a great analogy. I have to admit, that when I started this task I looked at AppDelegate and said to myself, "Well, clearly everything in SpriteBuilder goes in here!" and I didn't really look any farther than that. I am completely supportive of a concerted effort to refactor functionality into independent classes though so I will take a crack at it and update the pull request accordingly.

**Comment by thayerandrews** [comment]
@NickyWeber I've updated this pull request to move the majority of the lighting functionality out of AppDelegate and into LightingHandler. Let me know what you think.

**Comment by NickyWeber** [comment]
Very nice! On vacation at the moment, maybe @cocojoe could give it a spin and run tests as well then merge.

**Comment by cocojoe** [comment]
OK will take a look today.

On 15 December 2014 at 21:56, Nicky Weber notifications@github.com wrote:

> Very nice! On vacation at the moment, maybe @cocojoe
> https://github.com/cocojoe could give it a spin and run tests as well
> then merge.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spritebuilder/SpriteBuilder/pull/1205#issuecomment-67073509
> .

## 

Martin

**Comment by cocojoe** [comment]
@thayerandrews looks good so far, tests run fine.  Do you have a sample project with a nice sprite/normal map, I saw @vlidholt show off really nice SpriteBuilder fairy one.

**Comment by cocojoe** [comment]
@thayerandrews shall we discuss this later on in more detail? As I'm unsure of the expectations, for example I'm using a Directional light however it doesn't feel to me that it works as I would expect as a user.  I see values like cut-off radius and expect that I should see a visualisation of this in SB.

My mental comparison is being made against my experience of 3DS Max Lights Ux.

**Comment by thayerandrews** [comment]
@cocojoe, it sounds like you might not need it anymore but I've shared a simple lighting test project here: https://drive.google.com/file/d/0B7uVFeTINinAM0xkU3lxTDMxbnM/view?usp=sharing

**Comment by thayerandrews** [comment]
@cocojoe this is some good UX feedback. For directional lights, the cutoff radius doesn't matter so, if possible, it would be good for us to disable the radius controls. Also, for point lights where the radius matters, it would be good to display the cutoff and half radius values in the stage.

**Comment by cocojoe** [comment]
So code looks good, this feature will require a fair bit of documentation along with QA testing.  Let's get it going :)

**Pull request merged**
