### PR TITLE
Retina support

### LINKED ISSUE #705: Interface does not fully support retina
Several elements of the interface, such as the timeline, rules, and several icons are blurry on retina screens.

### PR DESCRIPTION
**Pull request by stuartcarnie**
Fixes #705 

I will continue to work through icons, but the base support for Retina displays is now there

### CODE REVIEW

**Comment by cocojoe** [comment]
Looking good so far, quite surprising how blurred non-retina looks once experienced :)

**Comment by stuartcarnie** [comment]
@cocojoe seriously, eh! It bugged me enough to work on it :)

**Comment by NickyWeber** [comment]
I can't test this on my old MBP, but this should be merged asap. This is very cool!

**Comment by cocojoe** [comment]
Yeah it's nice, it relies on change in Cocos2D so going to comment on that one first then happy to merge this in.  Would rather get it in and can always tweak any little bits that come up.

@stuartcarnie Great contribution thanks, will try and leave a few other parts of SB annoying for you ;)

**Comment by stuartcarnie** [comment]
No worries @cocojoe – I will probably experiment with a draggable numeric text field control next ;-)

**Comment by cocojoe** [comment]
Can no longer auto merge, also please remove the Cocos2D subproject change. Thx

**Comment by stuartcarnie** [comment]
Will do

**Comment by stuartcarnie** [comment]
@cocojoe pushed – you can auto-merge again and it refers back to the latest commit on cocos2d-swift/develop

**Comment by cocojoe** [comment]
Seems to have broken some tests, works if tested disabled, but needs looked at.

**Comment by stuartcarnie** [comment]
I'll take a look, @cocojoe. How do you run the tests?

**Comment by stuartcarnie** [comment]
I tried using the Test scheme in Xcode, and it all succeeded:

```
Test Suite 'SpriteBuilder Tests.xctest' passed at 2014-12-11 17:24:15 +0000.
     Executed 158 tests, with 0 failures (0 unexpected) in 2.355 (2.443) seconds
Test Suite 'All tests' passed at 2014-12-11 17:24:15 +0000.
     Executed 158 tests, with 0 failures (0 unexpected) in 2.355 (2.444) seconds
```

**Pull request merged**
